name: Run LaTeX on book

on:
   push:

jobs:
   latex:
      runs-on: ubuntu-latest
      steps:
        - run: sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
        - uses: actions/checkout@v2
        - run: touch includeonly.tex
        - run: pdflatex -interaction=nonstopmode -halt-on-error i1
        - run: bibtex i1
        - run: pdflatex -interaction=nonstopmode -halt-on-error i1
        - run: sed -i 's/\\"/"/g' i1.idx
        - run: sed -i 's/\\eingebaut/eingebaut/g' i1.idx
        - run: makeindex -c -s i1.mst -g i1
        - run: pdflatex -interaction=nonstopmode -halt-on-error i1 
